services:
  redis:
    container_name: redislocal
    hostname: redislocal
    image: redis:7.0.5-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass a7e48832-e6f9-4241-91c4-bd436487ba65
    environment:
      REDIS_HOST: redislocal
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  br-ms-sd00054-oi00003-ambassadorremittances:
    hostname: ${AMBASSADOR_HOSTNAME}
    build:
      context: ./br-ms-sd00054-oi00003-ambassadorremittances
      target: ${TARGET_STAGE}
    image: br-ms-sd00054-oi00003-ambassadorremittances:v1
    expose:
      - 3000
    ports:
      - 3000:8080
    depends_on:
      - redis
    volumes:
      - ./br-ms-sd00054-oi00003-ambassadorremittances/src:/app/src
      - ./br-ms-sd00054-oi00003-ambassadorremittances/node_modules:/app/node_modules

volumes:
  redis-data:

networks:
  default:
