---
services:
  redis:
    hostname: ${REDIS_HOSTNAME}
    image: redis:7.0.5-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_AUTH
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    volumes:
      - redis-data:/data
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 4001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
  pubsub:
    image: messagebird/gcloud-pubsub-emulator
    environment:
      - PUBSUB_PROJECT1=${PUB_SUB_PROJECT_ID},${PUB_SUB_TOPIC}:${PUB_SUB_SUBSCRIPTION}
    healthcheck:
      test: curl -fsS http://localhost:8681 || exit 1
      retries: 2
      interval: 10s
      start_period: 5s
      timeout: 5s
    # ports:
    #   - 8681:8681
  br-ms-sd00054-oi00003-ambassadorremittances:
    hostname: ${AMBASSADOR_REMITTANCES_HOSTNAME}
    build:
      context: ./br-ms-sd00054-oi00003-ambassadorremittances
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    ports:
      - 4080:8080
    depends_on:
      - redis
    volumes:
      - ./br-ms-sd00054-oi00003-ambassadorremittances/src:/app/src
  br-ms-sd00054-oi00005-ambassadorcorewallet:
    hostname: ${AMBASSADOR_CORE_WALLET_HOSTNAME}
    build:
      context: ./br-ms-sd00054-oi00005-ambassadorcorewallet
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      REDISHOST: ${REDIS_HOSTNAME}
      REDISAUTH: ${REDIS_AUTH}
    ports:
      - 4081:8080
    depends_on:
      - redis
    volumes:
      - ./br-ms-sd00054-oi00005-ambassadorcorewallet/src:/app/src
  br-ms-sd00103-oi00008-capturemoneycorewallet:
    hostname: ${CAPTURE_MONEY_CORE_WALLET_HOSTNAME}
    build:
      context: ./br-ms-sd00103-oi00008-capturemoneycorewallet
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_CORE_WALLET_URL}
    ports:
      - 4082:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet
    volumes:
      - ./br-ms-sd00103-oi00008-capturemoneycorewallet/src:/app/src
  br-ms-sd00102-oi00015-remittiancepayment:
    hostname: ${REMITTIANCE_PAYMENT_HOSTNAME}
    build:
      context: ./br-ms-sd00102-oi00015-remittiancepayment
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES_URL}
      WEBHOOK_URL: ${REMITTANCES_WEBHOOK_URL}
    ports:
      - 4083:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00102-oi00015-remittiancepayment/src:/app/src
  br-ms-sd00103-oi00012-corewalletsaga:
    build:
      context: ./br-ms-sd00103-oi00012-corewalletsaga
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      CAPTURE_MONEY_CORE_WALLET_URL: ${CAPTURE_MONEY_CORE_WALLET_URL}
      REMITTIANCE_PAYMENT_URL: ${REMITTIANCE_PAYMENT_URL}
      REVERSE_TECHNIQUE_CORE_WALLET_URL: ${REVERSE_TECHNIQUE_CORE_WALLET_URL}
      GET_INFORMATION_CHARGE_URL: ${GET_INFORMATION_CHARGE_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - 4084:8080
    depends_on:
      - br-ms-sd00102-oi00015-remittiancepayment
      - br-ms-sd00103-oi00008-capturemoneycorewallet
      - br-ms-sd00103-oi00011-reversetechniquecorewallet
      - br-ms-sd00103-io00013-getinformationcharge
      - mysql
      - phpmyadmin
    volumes:
      - ./br-ms-sd00103-oi00012-corewalletsaga/src:/app/src
  br-ms-sd00103-oi00011-reversetechniquecorewallet:
    hostname: ${REVERSE_TECHNIQUE_CORE_WALLET_HOSTNAME}
    build:
      context: ./br-ms-sd00103-oi00011-reversetechniquecorewallet
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_CORE_WALLET_URL}
    ports:
      - 4085:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet
    volumes:
      - ./br-ms-sd00103-oi00011-reversetechniquecorewallet/src:/app/src
  br-ms-sd00103-io00013-getinformationcharge:
    hostname: ${GET_INFORMATION_CHARGE_HOSTNAME}
    build:
      context: ./br-ms-sd00103-io00013-getinformationcharge
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_CORE_WALLET_URL}
    ports:
      - 4086:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet
    volumes:
      - ./br-ms-sd00103-io00013-getinformationcharge/src:/app/src
  br-ms-sd00103-oi00007-createpaymentcorewallet:
    build:
      context: ./br-ms-sd00103-oi00007-createpaymentcorewallet
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_CORE_WALLET_URL}
    ports:
      - 4087:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet
    volumes:
      - ./br-ms-sd00103-oi00007-createpaymentcorewallet/src:/app/src
  br-ms-sd00054-oi00003-ambassadorremittanceswebhook:
    build:
      context: ./br-ms-sd00054-oi00003-ambassadorremittanceswebhook
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      PUB_SUB_EMULATOR_HOST: ${PUB_SUB_EMULATOR_HOST}
      PUB_SUB_PROJECT_ID: ${PUB_SUB_PROJECT_ID}
      PUB_SUB_TOPIC: ${PUB_SUB_TOPIC}
      PUB_SUB_SUBSCRIPTION: ${PUB_SUB_SUBSCRIPTION}
      PUB_SUB_PUSH_ENDPOINT: ${PUB_SUB_PUSH_ENDPOINT}
    ports:
      - 4088:8080
    depends_on:
      pubsub:
        condition: service_healthy
    volumes:
      - ./br-ms-sd00054-oi00003-ambassadorremittanceswebhook/src:/app/src
  br-ms-sd00103-oi000013-corewalletsagacheckstate:
    build:
      context: ./br-ms-sd00103-oi000013-corewalletsagacheckstate
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      PUB_SUB_EMULATOR_HOST: ${PUB_SUB_EMULATOR_HOST}
      REVERSE_TECHNIQUE_CORE_WALLET_URL: ${REVERSE_TECHNIQUE_CORE_WALLET_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - 4089:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittanceswebhook
      - br-ms-sd00103-oi00011-reversetechniquecorewallet
      - mysql
      - phpmyadmin
    volumes:
      - ./br-ms-sd00103-oi000013-corewalletsagacheckstate/src:/app/src

volumes:
  redis-data:
  mysql-data:
