---
services:
  redis:
    hostname: ${REDIS_HOSTNAME}
    image: redis:7.0.5-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_AUTH
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    volumes:
      - redis-data:/data
  br-ms-sd00054-oi00003-ambassadorremittances:
    hostname: ${AMBASSADOR_HOSTNAME}
    build:
      context: ./br-ms-sd00054-oi00003-ambassadorremittances
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      REDISHOST: ${REDIS_HOSTNAME}
      REDISAUTH: ${REDIS_AUTH}
    ports:
      - 8080:8080
    depends_on:
      - redis
    volumes:
      - ./br-ms-sd00054-oi00003-ambassadorremittances/src:/app/src
  br-ms-sd00205-oi00007-getremittancepayers:
    build:
      context: ./br-ms-sd00205-oi00007-getremittancepayers
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES}
    ports:
      - 8081:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00205-oi00007-getremittancepayers/src:/app/src
  br-ms-sd00205-oi00006-getremittancebanks:
    build:
      context: ./br-ms-sd00205-oi00006-getremittancebanks
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES}
    ports:
      - 8082:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00205-oi00006-getremittancebanks/src:/app/src
  br-ms-sd00102-oi00016-webhookremittances:
    build:
      context: ./br-ms-sd00102-oi00016-webhookremittances
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES}
    ports:
      - 8083:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00102-oi00016-webhookremittances/src:/app/src
  br-ms-sd00102-oi00015-remittiancepayment:
    build:
      context: ./br-ms-sd00102-oi00015-remittiancepayment
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES}
    ports:
      - 8084:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00102-oi00015-remittiancepayment/src:/app/src
  br-ms-sd00205-oi00009-getremittanceflags:
    build:
      context: ./br-ms-sd00205-oi00009-getremittanceflags
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES}
    ports:
      - 8085:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00205-oi00009-getremittanceflags/src:/app/src
  br-ms-sd00103-io00004-createremittancequote:
    build:
      context: ./br-ms-sd00103-io00004-createremittancequote
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES}
    ports:
      - 8086:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00103-io00004-createremittancequote/src:/app/src
  br-ms-sd00103-oi00005-remittanceadmitquote:
    build:
      context: ./br-ms-sd00103-oi00005-remittanceadmitquote
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES}
    ports:
      - 8087:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00103-oi00005-remittanceadmitquote/src:/app/src
  br-ms-sd00205-oi00008-getremittancecountries:
    build:
      context: ./br-ms-sd00205-oi00008-getremittancecountries
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES}
    ports:
      - 8088:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00205-oi00008-getremittancecountries/src:/app/src

volumes:
  redis-data:
