---
services:
  redis:
    hostname: ${REDIS_HOSTNAME}
    image: redis:7.0.5-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_AUTH
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    # ports:
    #   - 6379:6379
    volumes:
      - redis-data:/data
  br-ms-sd00054-oi00005-ambassadorcorewallet:
    hostname: ${AMBASSADOR_HOSTNAME}
    build:
      context: ./br-ms-sd00054-oi00005-ambassadorcorewallet
      target: ${TARGET_STAGE}
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    ports:
      - 3080:8080
    depends_on:
      - redis
  br-ms-sd00103-oi00007-createpaymentcorewallet:
    build:
      context: ./br-ms-sd00103-oi00007-createpaymentcorewallet
      target: ${TARGET_STAGE}
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_URL}
    ports:
      - 3081:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet

volumes:
  redis-data:
