---
services:
  redis:
    hostname: ${REDIS_HOSTNAME}
    image: redis:7.0.5-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
    # ports:
    #   - 6379:6379
    volumes:
      - redis-data:/data
  br-ms-sd00270-oi00019-smsprovider:
    build:
      context: ./br-ms-sd00270-oi00019-smsprovider
      target: ${TARGET_STAGE}
    # TODO: Add environment variables
    ports:
      - 5080:8080
    volumes:
      - ./br-ms-sd00270-oi00019-smsprovider/src:/app/src
  br-ms-sd00270-oi00017-createotp:
    build:
      context: ./br-ms-sd00270-oi00017-createotp
      target: ${TARGET_STAGE}
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
    ports:
      - 5081:8080
    depends_on:
      - redis
      - br-ms-sd00270-oi00019-smsprovider
    volumes:
      - ./br-ms-sd00270-oi00017-createotp/src:/app/src
  br-ms-sd00270-oi00018-validateotp:
    build:
      context: ./br-ms-sd00270-oi00018-validateotp
      target: ${TARGET_STAGE}
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
    ports:
      - 5082:8080
    depends_on:
      - redis
    volumes:
      - ./br-ms-sd00270-oi00018-validateotp/src:/app/src
  br-ms-sd00270-oi00020-updateotp:
    build:
      context: ./br-ms-sd00270-oi00020-updateotp
      target: ${TARGET_STAGE}
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
    ports:
      - 5083:8080
    depends_on:
      - redis
      - br-ms-sd00270-oi00019-smsprovider
    volumes:
      - ./br-ms-sd00270-oi00020-updateotp/src:/app/src
  br-ms-sd00270-oi00016-otphandler:
    build:
      context: ./br-ms-sd00270-oi00016-otphandler
      target: ${TARGET_STAGE}
    # TODO: Add environment variables
    ports:
      - 5084:8080
    depends_on:
      - br-ms-sd00270-oi00017-createotp
      - br-ms-sd00270-oi00018-validateotp
      - br-ms-sd00270-oi00020-updateotp
    volumes:
      - ./br-ms-sd00270-oi00016-otphandler/src:/app/src

volumes:
  redis-data:
