---
services:
  redis:
    hostname: ${REDIS_HOSTNAME}
    image: redis:7.0.5-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_AUTH
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    # ports:
    #   - 6379:6379
    volumes:
      - redis-data:/data
  br-ms-sd00054-oi00003-ambassadorremittances:
    hostname: ${AMBASSADOR_REMITTANCES_HOSTNAME}
    build:
      context: ./br-ms-sd00054-oi00003-ambassadorremittances
      target: ${TARGET_STAGE}
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    ports:
      - 4080:8080
    depends_on:
      - redis
    volumes:
      - ./br-ms-sd00054-oi00003-ambassadorremittances/src:/app/src
  br-ms-sd00054-oi00005-ambassadorcorewallet:
    hostname: ${AMBASSADOR_CORE_WALLET_HOSTNAME}
    build:
      context: ./br-ms-sd00054-oi00005-ambassadorcorewallet
      target: ${TARGET_STAGE}
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    ports:
      - 4081:8080
    depends_on:
      - redis
    volumes:
      - ./br-ms-sd00054-oi00005-ambassadorcorewallet/src:/app/src
  br-ms-sd00103-oi00008-capturemoneycorewallet:
    hostname: ${CAPTURE_MONEY_CORE_WALLET_HOSTNAME}
    build:
      context: ./br-ms-sd00103-oi00008-capturemoneycorewallet
      target: ${TARGET_STAGE}
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_CORE_WALLET_URL}
    ports:
      - 4082:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet
    volumes:
      - ./br-ms-sd00103-oi00008-capturemoneycorewallet/src:/app/src
  br-ms-sd00102-oi00015-remittiancepayment:
    hostname: ${REMITTIANCE_PAYMENT_HOSTNAME}
    build:
      context: ./br-ms-sd00102-oi00015-remittiancepayment
      target: ${TARGET_STAGE}
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES_URL}
    ports:
      - 4083:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00102-oi00015-remittiancepayment/src:/app/src
  br-ms-sd00103-oi00012-corewalletsaga:
    build:
      context: ./br-ms-sd00103-oi00012-corewalletsaga
      target: ${TARGET_STAGE}
    environment:
      CAPTURE_MONEY_CORE_WALLET_URL: ${CAPTURE_MONEY_CORE_WALLET_URL}
      REMITTIANCE_PAYMENT_URL: ${REMITTIANCE_PAYMENT_URL}
    ports:
      - 4084:8080
    depends_on:
      - br-ms-sd00102-oi00015-remittiancepayment
      - br-ms-sd00103-oi00008-capturemoneycorewallet
    volumes:
      - ./br-ms-sd00103-oi00012-corewalletsaga/src:/app/src

volumes:
  redis-data:
