---
services:
  br-ms-sd00054-oi00005-ambassadorcorewallet:
    volumes:
      - ./br-ms-sd00054-oi00005-ambassadorcorewallet/src:/app/src
      - ./br-ms-sd00054-oi00005-ambassadorcorewallet/node_modules:/app/node_modules
  br-ms-sd00103-oi00007-createpaymentcorewallet:
    volumes:
      - ./br-ms-sd00103-oi00007-createpaymentcorewallet/src:/app/src
      - ./br-ms-sd00103-oi00007-createpaymentcorewallet/node_modules:/app/node_modules
