---
services:
  redis:
    hostname: ${REDIS_HOSTNAME}
    image: redis:7.0.5-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_AUTH
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    volumes:
      - redis-data:/data
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 4001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
  pubsub:
    image: messagebird/gcloud-pubsub-emulator
    environment:
      - PUBSUB_PROJECT1=${PUB_SUB_PROJECT_ID},${PUB_SUB_TOPIC_REMITTANCE}:${PUB_SUB_SUBSCRIPTION_REMITTANCE}
      - PUBSUB_PROJECT2=${PUB_SUB_PROJECT_ID},${PUB_SUB_TOPIC_HEY_PAY}:${PUB_SUB_SUBSCRIPTION_HEY_PAY}
    healthcheck:
      test: curl -fsS http://localhost:8681 || exit 1
      retries: 2
      interval: 10s
      start_period: 5s
      timeout: 5s
    # ports:
    #   - 8681:8681
  br-ms-sd00054-oi00003-ambassadorremittances:
    hostname: ${AMBASSADOR_REMITTANCES_HOSTNAME}
    build:
      context: ./br-ms-sd00054-oi00003-ambassadorremittances
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_AUTH: ${REDIS_AUTH}
    ports:
      - 4080:8080
    depends_on:
      - redis
    volumes:
      - ./br-ms-sd00054-oi00003-ambassadorremittances/src:/app/src
  br-ms-sd00054-oi00005-ambassadorcorewallet:
    hostname: ${AMBASSADOR_CORE_WALLET_HOSTNAME}
    build:
      context: ./br-ms-sd00054-oi00005-ambassadorcorewallet
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      REDISHOST: ${REDIS_HOSTNAME}
      REDISAUTH: ${REDIS_AUTH}
    ports:
      - 4081:8080
    depends_on:
      - redis
    volumes:
      - ./br-ms-sd00054-oi00005-ambassadorcorewallet/src:/app/src
  br-ms-sd00103-oi00008-capturemoneycorewallet:
    hostname: ${CAPTURE_MONEY_CORE_WALLET_HOSTNAME}
    build:
      context: ./br-ms-sd00103-oi00008-capturemoneycorewallet
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_CORE_WALLET_URL}
    ports:
      - 4082:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet
    volumes:
      - ./br-ms-sd00103-oi00008-capturemoneycorewallet/src:/app/src
  br-ms-sd00102-oi00015-remittiancepayment:
    hostname: ${REMITTIANCE_PAYMENT_HOSTNAME}
    build:
      context: ./br-ms-sd00102-oi00015-remittiancepayment
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_REMITTANCES: ${AMBASSADOR_REMITTANCES_URL}
      WEBHOOK_URL: ${REMITTANCES_WEBHOOK_URL}
    ports:
      - 4083:8080
    depends_on:
      - br-ms-sd00054-oi00003-ambassadorremittances
    volumes:
      - ./br-ms-sd00102-oi00015-remittiancepayment/src:/app/src
  br-ms-sd00103-oi00012-corewalletsaga:
    build:
      context: ./br-ms-sd00103-oi00012-corewalletsaga
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      CAPTURE_MONEY_CORE_WALLET_URL: ${CAPTURE_MONEY_CORE_WALLET_URL}
      REMITTIANCE_PAYMENT_URL: ${REMITTIANCE_PAYMENT_URL}
      REVERSE_TECHNIQUE_CORE_WALLET_URL: ${REVERSE_TECHNIQUE_CORE_WALLET_URL}
      GET_INFORMATION_CHARGE_URL: ${GET_INFORMATION_CHARGE_URL}
      SAVE_MOVEMENTS_URL: ${SAVE_MOVEMENTS_URL}
      SEND_EMAIL_URL: ${SEND_EMAIL_URL}
    ports:
      - 4084:8080
    depends_on:
      - br-ms-sd00102-oi00015-remittiancepayment
      - br-ms-sd00103-oi00008-capturemoneycorewallet
      - br-ms-sd00103-oi00011-reversetechniquecorewallet
      - br-ms-sd00103-io00013-getinformationcharge
      - br-ms-sd00103-oi00016-savemovements
      - br-ms-sd00025-oi00004-sendemail
    volumes:
      - ./br-ms-sd00103-oi00012-corewalletsaga/src:/app/src
  br-ms-sd00103-oi00011-reversetechniquecorewallet:
    hostname: ${REVERSE_TECHNIQUE_CORE_WALLET_HOSTNAME}
    build:
      context: ./br-ms-sd00103-oi00011-reversetechniquecorewallet
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_CORE_WALLET_URL}
    ports:
      - 4085:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet
    volumes:
      - ./br-ms-sd00103-oi00011-reversetechniquecorewallet/src:/app/src
  br-ms-sd00103-io00013-getinformationcharge:
    hostname: ${GET_INFORMATION_CHARGE_HOSTNAME}
    build:
      context: ./br-ms-sd00103-io00013-getinformationcharge
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_CORE_WALLET_URL}
    ports:
      - 4086:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet
    volumes:
      - ./br-ms-sd00103-io00013-getinformationcharge/src:/app/src
  br-ms-sd00103-oi00007-createpaymentcorewallet:
    build:
      context: ./br-ms-sd00103-oi00007-createpaymentcorewallet
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      AMBASSADOR_URL: ${AMBASSADOR_CORE_WALLET_URL}
    ports:
      - 4087:8080
    depends_on:
      - br-ms-sd00054-oi00005-ambassadorcorewallet
    volumes:
      - ./br-ms-sd00103-oi00007-createpaymentcorewallet/src:/app/src
  br-ms-sd00102-oi00016-remittancestatusnotification:
    build:
      context: ./br-ms-sd00102-oi00016-remittancestatusnotification
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      PUB_SUB_EMULATOR_HOST: ${PUB_SUB_EMULATOR_HOST}
      PUB_SUB_PROJECT_ID: ${PUB_SUB_PROJECT_ID}
      PUB_SUB_TOPIC: ${PUB_SUB_TOPIC_REMITTANCE}
      PUB_SUB_SUBSCRIPTION: ${PUB_SUB_SUBSCRIPTION_REMITTANCE}
      PUB_SUB_PATTERN: ${PUB_SUB_PATTERN_REMITTANCE}
      PUB_SUB_PUSH_ENDPOINT: ${PUB_SUB_PUSH_ENDPOINT_REMITTANCE}
    ports:
      - 4088:8080
    depends_on:
      pubsub:
        condition: service_healthy
    volumes:
      - ./br-ms-sd00102-oi00016-remittancestatusnotification/src:/app/src
  br-ms-sd00103-oi00014-processremittancestatus:
    hostname: ${PROCESS_STATUS_HOSTNAME}
    build:
      context: ./br-ms-sd00103-oi00014-processremittancestatus
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      PUB_SUB_EMULATOR_HOST: ${PUB_SUB_EMULATOR_HOST}
      REVERSE_TECHNIQUE_CORE_WALLET_URL: ${REVERSE_TECHNIQUE_CORE_WALLET_URL}
      GET_MOVEMENTS_URL: ${GET_MOVEMENTS_URL}
      SAVE_MOVEMENTS_URL: ${SAVE_MOVEMENTS_URL}
      SEND_EMAIL_SERVICE_URL: ${SEND_EMAIL_URL}
    ports:
      - 4089:8080
    depends_on:
      - br-ms-sd00102-oi00016-remittancestatusnotification
      - br-ms-sd00103-oi00011-reversetechniquecorewallet
      - br-ms-sd00103-oi00017-getmovements
      - br-ms-sd00103-oi00016-savemovements
      - br-ms-sd00025-oi00004-sendemail
    volumes:
      - ./br-ms-sd00103-oi00014-processremittancestatus/src:/app/src
  br-ms-sd00103-oi00016-savemovements:
    hostname: ${SAVE_MOVEMENTS_HOSTNAME}
    build:
      context: ./br-ms-sd00103-oi00016-savemovements
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - 4090:8080
    depends_on:
      - mysql
      - phpmyadmin
    volumes:
      - ./br-ms-sd00103-oi00016-savemovements/src:/app/src
  br-ms-sd00103-oi00017-getmovements:
    hostname: ${GET_MOVEMENTS_HOSTNAME}
    build:
      context: ./br-ms-sd00103-oi00017-getmovements
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - 4091:8080
    depends_on:
      - mysql
      - phpmyadmin
    volumes:
      - ./br-ms-sd00103-oi00017-getmovements/src:/app/src
  br-ms-sd00025-oi00004-sendemail:
    hostname: ${SEND_EMAIL_HOSTNAME}
    build:
      context: ./br-ms-sd00025-oi00004-sendemail
      target: ${TARGET_STAGE}
      dockerfile: Dockerfile.dev
    environment:
      URL_SENDGRID_AMBASSADOR: http://localhost:3000
    ports:
      - 4092:8080
    volumes:
      - ./br-ms-sd00025-oi00004-sendemail/src:/app/src
  br-ms-sd00000-oi00000-walletauthorizationnotification:
    build:
      context: ./br-ms-sd00000-oi00000-walletauthorizationnotification
      target: dev
      dockerfile: Dockerfile.dev
    environment:
      - PUB_SUB_EMULATOR_HOST=${PUB_SUB_EMULATOR_HOST}
      - PUB_SUB_PROJECT_ID=${PUB_SUB_PROJECT_ID}
      - PUB_SUB_TOPIC=${PUB_SUB_TOPIC_HEY_PAY}
      - PUB_SUB_SUBSCRIPTION=${PUB_SUB_SUBSCRIPTION_HEY_PAY}
      - PUB_SUB_PATTERN=${PUB_SUB_PATTERN_HEY_PAY}
      - PUB_SUB_PUSH_ENDPOINT=${PUB_SUB_PUSH_ENDPOINT_HEY_PAY}
    ports:
      - 4093:8080
    depends_on:
      - pubsub
      - br-ms-sd00000-oi00000-processwalletauthorization
    volumes:
      - ./br-ms-sd00000-oi00000-walletauthorizationnotification/src:/app/src
  br-ms-sd00000-oi00000-processwalletauthorization:
    build:
      context: ./br-ms-sd00000-oi00000-processwalletauthorization
      target: dev
      dockerfile: Dockerfile.dev
    environment:
      UPDATE_REMITTANCE_URL: ${UPDATE_REMITTANCE_URL}
      CORE_WALLET_SAGA_URL: ${CORE_WALLET_SAGA_URL}
    ports:
      - 4094:8080
    volumes:
      - ./br-ms-sd00000-oi00000-processwalletauthorization/src:/app/src

volumes:
  redis-data:
  mysql-data:
